# Generated by Django 4.1.7 on 2023-05-18 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='user_photos'),
            preserve_default=False,
        ),
    ]
