# Generated by Django 4.1.7 on 2023-05-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
